---
- name: Zip the logs
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: log files older than 90 days
      shell: "find /var/log/httpd/ -type f -name *.log -mtime +90 -exec gzip -9 {} \; "