- name: EC2 state (start, stop, restart,)
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - ec2:
        instance_ids: "{{instance_ids}}"
        state: "{{state}}"
        region: "{{region}}"

        
