- name: Security Group  
  hosts: localhost
  tasks:
  - name: example using security group rule descriptions
    ec2_group:
      name: my-SG-1
      description: My SG1
      vpc_id: vpc-46395b20
      region: eu-west-1
      resource_tags:
        Name: my-SG-1
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 22
          cidr_ip: 
            - 162.158.78.182/32
